### ISSUE TITLE
[Feature] popular state management observers

### ISSUE THREAD

**Issue by XanderD99** [unger1984/trackit#1]
As the title suggests observers for the more popular state management observers, such as Bloc, Riverpod, ....

This can just grow organically when needed I suppose

**Comment by unger1984** [comment]
I think there is no need to make separate packages for this. It would be better to write in the documentation how to make observers for the most popular packages. Usually there is only one class. Will this solution be ok?

**Comment by unger1984** [comment]
For example https://github.com/unger1984/trackit?tab=readme-ov-file#how-to-use-with-bloc

**Comment by XanderD99** [comment]
oh Yeah that may even be a better idea!
